[greeter]
theme-name = FutureOS-Dark
icon-theme-name = FutureOS
font-name = Inter 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
background = /usr/share/future-os/wallpapers/default.png
user-background = false
clock-format = %H:%M - %A %d %B
show-indicators = ~host;~spacer;~clock;~spacer;~session;~power
show-clock = true
panel-position = top
position = 50%,center 50%,center
